version: '3.8'
name: nawy-cluster

services:
  ui:
    build:
      context: nawy.ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: npm run start
    depends_on:
      app:
        condition: service_started

  app:
    build:
      context: nawy.api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: sqlserver://db:1433;user=sa;password=Mario1234!;trustServerCertificate=true;poolTimeout=60;
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_started

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      DATABASE_URL: "sqlserver://db:1433;user=sa;password=Mario1234!;trustServerCertificate=true;"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: Mario1234!
      ACCEPT_EULA: Y
    ports:
      - "1313:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Mario1234! -Q 'SELECT 1'"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
